web_packages:
  - iceweasel
  - iceweasel-vimperator
  - xul-ext-adblock-plus
  - xul-ext-firebug
  - xul-ext-https-everywhere
  - xul-ext-livehttpheaders
  - xul-ext-noscript
  - flashplugin-nonfree
  - google-chrome-stable
  - keepassx
  - deluge
