#!/bin/sh

set -e

lb config noauto \
  --apt aptitude \
  --architectures amd64 \
  --archive-areas "main" \
  --checksums sha1 \
  --debian-installer live \
  --debian-installer-distribution testing \
  --distribution testing \
  "${@}"
